### ISSUE TITLE
필요없는 로그 제거하기

### ISSUE THREAD

**Issue by jihyehann** [Zeroway-GreenFriends/Zeroway-Server#99]
- AOP를 통해 로그를 남기는 로직을 한 곳으로 모았기 때문에, 현재 메인 로직에 직접 로그를 출력하는 부분은 대부분 필요가 없음.
- 특히 `e.printStackTrace()` 는 성능 상의 문제가 될 수 있으므로 반드시 제거하기! [참고](https://tgyun615.com/59)

**Comment by yeeeze** [comment]
#103 수정 완료

**Comment by sojungpp** [comment]
#104 수정 완료
